<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Didww.Api3</RootNamespace>
    <PackageId>Didww.Api3</PackageId>
    <Version>3.2.0</Version>
    <Authors>DIDWW</Authors>
    <Description>DIDWW API v3 SDK for .NET</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/didww/didww-api-3-dotnet-sdk</PackageProjectUrl>
    <RepositoryUrl>https://github.com/didww/didww-api-3-dotnet-sdk</RepositoryUrl>
    <PackageTags>didww;api;voip;did;telephony</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Didww.Api3.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JsonApiSerializer" Version="2.0.1" />
  </ItemGroup>

</Project>
